### ISSUE TITLE
Cant install this package because I get error: MINISAT-out: Cannot enlarge memory arrays.

### ISSUE THREAD

**Issue by sferoze** [rissem/meteor-electron#108]
Whenever I try to install this package into my Meteor 1.4 app I get the error

```
MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

/Users/Nearpoint/.meteor/packages/meteor-tool/.1.4.1_2.1r2z6b4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^
abort() at Error
    at jsStackTrace (packages/logic-solver/minisat.js:3:1)
    at stackTrace (packages/logic-solver/minisat.js:3:1)
    at abort (packages/logic-solver/minisat.js:33:1)
    at enlargeMemory (packages/logic-solver/minisat.js:3:1)
    at Function.Runtime.dynamicAlloc [as alloc] (packages/logic-solver/minisat.js:3:1)
    at _sbrk (packages/logic-solver/minisat.js:3:1)
    at Sd (packages/logic-solver/minisat.js:7:1)
    at Ud (packages/logic-solver/minisat.js:7:1)
    at gc (packages/logic-solver/minisat.js:7:1)
    at pc (packages/logic-solver/minisat.js:7:1)
    at Kb (packages/logic-solver/minisat.js:7:1)
    at Dc (packages/logic-solver/minisat.js:7:1)
    at Object.dd [as _addClause] (packages/logic-solver/minisat.js:7:1)
    at packages/logic-solver/minisat_wrapper.js:74:1
    at Object._native.savingStack (packages/logic-solver/minisat_wrapper.js:37:1)
    at [object Object].MiniSat.addClause (packages/logic-solver/minisat_wrapper.js:68:1)
    at [object Object].Logic.Solver.solve (packages/logic-solver/logic.js:1326:1)
    at [object Object].Logic.Solver.solveAssuming (packages/logic-solver/logic.js:1369:1)
    at minMaxWS (packages/logic-solver/optimize.js:52:1)
    at [object Object].Logic.Solver.minimizeWeightedSum (packages/logic-solver/optimize.js:139:1)
    at packages/constraint-solver/solver.js:368:1
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object].CS.Solver.minimize (packages/constraint-solver/solver.js:352:1)
    at [object Object].CS.Solver.minimize (packages/constraint-solver/solver.js:346:1)
    at [object Object].CS.Solver._getAnswer (packages/constraint-solver/solver.js:735:1)
    at packages/constraint-solver/solver.js:603:1
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object].CS.Solver.getAnswer (packages/constraint-solver/solver.js:602:1)
    at packages/constraint-solver/constraint-solver.js:165:1
    at Object.Logic.disablingAssertions (packages/logic-solver/logic.js:45:1)
    at Function.CS.PackagesResolver._resolveWithInput (packages/constraint-solver/constraint-solver.js:164:1)
    at [object Object].CS.PackagesResolver.resolve (packages/constraint-solver/constraint-solver.js:128:1)
    at /tools/project-context.js:518:35
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/project-context.js:514:19
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:486:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._resolveConstraints (/tools/project-context.js:485:13)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/cli/commands-packages.js:2034:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Command.func (/tools/cli/commands-packages.js:2033:27)
    at /tools/cli/main.js:1410:23
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

Any suggestions on how to get this working?

**Comment by elidiazgt** [comment]
i have the same problem, im using 16gb of memory in my machine

**Comment by macsj200** [comment]
Just to keep y'all appraised, you're probably having a similar issue to [meteor issue 7533](https://github.com/meteor/meteor/issues/7533).
