### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by appinteractive** [rissem/meteor-electron#67]
Getting the following output when trying to start meteor with you package on OS X:

```
meteor

=> Started proxy.
=> Started MongoDB.
Downloading electron-v0.36.2-darwin-x64.zip
I20160218-22:58:10.304(1)? [============================================>] 100.0% of 39.34 MB (389.51 kB/s)
W20160218-22:58:10.352(1)? (STDERR) Packaging app for platform darwin x64 using electron v0.36.2
I20160218-22:58:13.383(1)? Build created for  darwin x64 at /Users/x/meteor/electron/.meteor-electron/darwin-x64/builds/Electron-darwin-x64
W20160218-22:58:13.406(1)? (STDERR)
W20160218-22:58:13.406(1)? (STDERR)         throw er; // Unhandled 'error' event
W20160218-22:58:13.407(1)? (STDERR) Error: spawn ENOENT
W20160218-22:58:13.406(1)? (STDERR) events.js:72
W20160218-22:58:13.408(1)? (STDERR)     at errnoException (child_process.js:1011:11)
W20160218-22:58:13.408(1)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
W20160218-22:58:13.406(1)? (STDERR)               ^
=> Exited with code: 8
```

Its the only installed package on a newly created project.

**Comment by yogiben** [comment]
+1

**Comment by MartinBucko** [comment]
Same here on Ubuntu 15.10 with Meteor 1.3.1 and  NodeJS v0.10.42:

```

W20160409-03:50:51.689(2)? (STDERR) Packaging app for platform linux x64 using electron v0.36.2
I20160409-03:50:52.753(2)? Build created for  linux x64 at /home/myappfolder/.meteor-electron/linux-x64/builds/Mercur Playout-linux-x64
W20160409-03:50:52.765(2)? (STDERR) 
W20160409-03:50:52.766(2)? (STDERR) events.js:72
W20160409-03:50:52.766(2)? (STDERR)         throw er; // Unhandled 'error' event
W20160409-03:50:52.766(2)? (STDERR)               ^
W20160409-03:50:52.767(2)? (STDERR) Error: spawn ENOENT
W20160409-03:50:52.768(2)? (STDERR)     at errnoException (child_process.js:1011:11)
W20160409-03:50:52.768(2)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
=> Exited with code: 8

```
